<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="1" total="7" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-08-12T15:12:16 IST" name="Suite" finished-at="2024-08-12T15:13:39 IST" duration-ms="82894">
    <groups>
      <group name="ErrorHandling">
        <method signature="LoginError.loginErrorValidation()[pri:0, instance:Perficient.SeleniumFrameworkDesign.LoginError@6187d1f5]" name="loginErrorValidation" class="Perficient.SeleniumFrameworkDesign.LoginError"/>
      </group> <!-- ErrorHandling -->
      <group name="purchase">
        <method signature="pageObject.submitOrder(java.util.HashMap)[pri:0, instance:Perficient.SeleniumFrameworkDesign.pageObject@5a1de7fb]" name="submitOrder" class="Perficient.SeleniumFrameworkDesign.pageObject"/>
      </group> <!-- purchase -->
    </groups>
    <test started-at="2024-08-12T15:12:16 IST" name="Functional_Tests" finished-at="2024-08-12T15:13:02 IST" duration-ms="46484">
      <class name="Perficient.SeleniumFrameworkDesign.pageObject">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Perficient.SeleniumFrameworkDesign.pageObject@5a1de7fb]" started-at="2024-08-12T15:12:16 IST" name="launchApplication" finished-at="2024-08-12T15:12:23 IST" duration-ms="6707" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:Perficient.SeleniumFrameworkDesign.pageObject@5a1de7fb]" started-at="2024-08-12T15:12:23 IST" name="submitOrder" data-provider="getData" finished-at="2024-08-12T15:12:39 IST" duration-ms="16423" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Test@123, product=ZARA COAT 3, email=divyak@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="quitDriver()[pri:0, instance:Perficient.SeleniumFrameworkDesign.pageObject@5a1de7fb]" started-at="2024-08-12T15:12:39 IST" name="quitDriver" finished-at="2024-08-12T15:12:40 IST" duration-ms="613" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitDriver -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Perficient.SeleniumFrameworkDesign.pageObject@5a1de7fb]" started-at="2024-08-12T15:12:40 IST" name="launchApplication" finished-at="2024-08-12T15:12:42 IST" duration-ms="1861" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:Perficient.SeleniumFrameworkDesign.pageObject@5a1de7fb]" started-at="2024-08-12T15:12:42 IST" name="submitOrder" data-provider="getData" finished-at="2024-08-12T15:12:58 IST" duration-ms="16178" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Iamking@000, product=ADIDAS ORIGINAL, email=anshika@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="quitDriver()[pri:0, instance:Perficient.SeleniumFrameworkDesign.pageObject@5a1de7fb]" started-at="2024-08-12T15:12:58 IST" name="quitDriver" finished-at="2024-08-12T15:12:58 IST" duration-ms="390" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitDriver -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Perficient.SeleniumFrameworkDesign.pageObject@5a1de7fb]" started-at="2024-08-12T15:12:58 IST" name="launchApplication" finished-at="2024-08-12T15:13:01 IST" duration-ms="2675" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="OrderList()[pri:0, instance:Perficient.SeleniumFrameworkDesign.pageObject@5a1de7fb]" started-at="2024-08-12T15:13:01 IST" name="OrderList" finished-at="2024-08-12T15:13:02 IST" depends-on-methods="Perficient.SeleniumFrameworkDesign.pageObject.submitOrder" duration-ms="1057" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OrderList -->
        <test-method is-config="true" signature="quitDriver()[pri:0, instance:Perficient.SeleniumFrameworkDesign.pageObject@5a1de7fb]" started-at="2024-08-12T15:13:02 IST" name="quitDriver" finished-at="2024-08-12T15:13:02 IST" duration-ms="260" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitDriver -->
      </class> <!-- Perficient.SeleniumFrameworkDesign.pageObject -->
    </test> <!-- Functional_Tests -->
    <test started-at="2024-08-12T15:13:03 IST" name="ErrorValidation_Tests" finished-at="2024-08-12T15:13:39 IST" duration-ms="36062">
      <class name="Perficient.SeleniumFrameworkDesign.LoginError">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Perficient.SeleniumFrameworkDesign.LoginError@6187d1f5]" started-at="2024-08-12T15:13:03 IST" name="launchApplication" finished-at="2024-08-12T15:13:06 IST" duration-ms="3271" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="loginErrorValidation()[pri:0, instance:Perficient.SeleniumFrameworkDesign.LoginError@6187d1f5]" started-at="2024-08-12T15:13:06 IST" name="loginErrorValidation" finished-at="2024-08-12T15:13:07 IST" duration-ms="765" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidation -->
        <test-method is-config="true" signature="quitDriver()[pri:0, instance:Perficient.SeleniumFrameworkDesign.LoginError@6187d1f5]" started-at="2024-08-12T15:13:07 IST" name="quitDriver" finished-at="2024-08-12T15:13:07 IST" duration-ms="237" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitDriver -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Perficient.SeleniumFrameworkDesign.LoginError@6187d1f5]" started-at="2024-08-12T15:13:07 IST" name="launchApplication" finished-at="2024-08-12T15:13:09 IST" duration-ms="1704" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="productErrorValidation()[pri:0, instance:Perficient.SeleniumFrameworkDesign.LoginError@6187d1f5]" started-at="2024-08-12T15:13:09 IST" name="productErrorValidation" finished-at="2024-08-12T15:13:22 IST" duration-ms="13774" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at Perficient.SeleniumFrameworkDesign.LoginError.productErrorValidation(LoginError.java:30)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- productErrorValidation -->
        <test-method is-config="true" signature="quitDriver()[pri:0, instance:Perficient.SeleniumFrameworkDesign.LoginError@6187d1f5]" started-at="2024-08-12T15:13:22 IST" name="quitDriver" finished-at="2024-08-12T15:13:23 IST" duration-ms="315" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitDriver -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Perficient.SeleniumFrameworkDesign.LoginError@6187d1f5]" started-at="2024-08-12T15:13:23 IST" name="launchApplication" finished-at="2024-08-12T15:13:24 IST" duration-ms="1715" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="productErrorValidation()[pri:0, instance:Perficient.SeleniumFrameworkDesign.LoginError@6187d1f5]" started-at="2024-08-12T15:13:24 IST" name="productErrorValidation" finished-at="2024-08-12T15:13:38 IST" duration-ms="13772" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at Perficient.SeleniumFrameworkDesign.LoginError.productErrorValidation(LoginError.java:30)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- productErrorValidation -->
        <test-method is-config="true" signature="quitDriver()[pri:0, instance:Perficient.SeleniumFrameworkDesign.LoginError@6187d1f5]" started-at="2024-08-12T15:13:38 IST" name="quitDriver" finished-at="2024-08-12T15:13:39 IST" duration-ms="332" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitDriver -->
      </class> <!-- Perficient.SeleniumFrameworkDesign.LoginError -->
    </test> <!-- ErrorValidation_Tests -->
  </suite> <!-- Suite -->
</testng-results>
